# Generated by Django 2.2.3 on 2019-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x_coord',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coord',
            field=models.IntegerField(default=10),
        ),
    ]
